/**
 * Write deployments.json into the web app's environment.
 *
 * The contract id and the settlement asset live in one place in this repo;
 * syncing them here means a fresh clone needs no copy-paste before `pnpm dev`.
 */
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { loadDeployments } from "./deployments.mjs";
import { NETWORKS } from "./networks.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const webDir = join(here, "..", "apps", "web");

const d = loadDeployments();
const t = d.testnet ?? {};
const m = d.mainnet ?? {};

const lines = [
  "# generated by scripts/sync-env.mjs — do not edit by hand",
  "",
  "NEXT_PUBLIC_NETWORK=testnet",
  "",
  `# Proved contract, testnet (${t.contractId ?? "not deployed"})`,
  `NEXT_PUBLIC_CONTRACT_TESTNET=${t.contractId ?? ""}`,
  "",
  `# Proved contract, mainnet (${m.contractId ?? "not deployed"})`,
  `NEXT_PUBLIC_CONTRACT_MAINNET=${m.contractId ?? ""}`,
  "",
  "# Soroban RPC",
  `NEXT_PUBLIC_RPC_TESTNET=${NETWORKS.testnet.rpcUrl}`,
  `NEXT_PUBLIC_RPC_MAINNET=${NETWORKS.mainnet.rpcUrl}`,
  "",
  "# Settlement asset",
  // A job that has actually settled on testnet, pre-filled into the site's job
  // field. Replaced by hand when a newer job is settled; the point is that the
  // id a judge lands on resolves to a real released payment.
  `NEXT_PUBLIC_SHOWCASE_JOB_TESTNET=41c43d954bf7330cb849437f6a5c92f7d763eb24882f64078e8a30ac2dab0382`,
  `NEXT_PUBLIC_SHOWCASE_JOB_DISPUTED_TESTNET=670e65eedd7abc05bf1356e58ef987aff6f1c035a85af014ec7b6576939d74a9`,
  // Mainnet has no funded job: deploying needs ~24 XLM and four funded accounts
  // to move real USDC. Empty, and the switcher says so rather than pre-filling
  // an id that does not exist.
  `NEXT_PUBLIC_SHOWCASE_JOB_MAINNET=`,
  `NEXT_PUBLIC_ASSET_CODE_TESTNET=${t.assetCode ?? "PUSD"}`,
  `NEXT_PUBLIC_ASSET_CONTRACT_TESTNET=${t.asset ?? ""}`,
  `NEXT_PUBLIC_USDC_MAINNET=${m.asset || NETWORKS.mainnet.usdc}`,
  "",
];

const out = join(webDir, ".env.local");
writeFileSync(out, lines.join("\n"));
console.log("wrote", out);
if (!t.contractId) {
  console.warn("\nno testnet deployment recorded yet — run: pnpm run deploy:testnet");
}
