/**
 * Write deployments.json into the web app's environment.
 *
 * The contract id and the settlement asset live in one place in this repo;
 * syncing them here means a fresh clone needs no copy-paste before `pnpm dev`.
 */
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { loadDeployments } from "./deployments.mjs";
import { NETWORKS } from "./networks.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const webDir = join(here, "..", "apps", "web");

const d = loadDeployments();
const t = d.testnet ?? {};
const m = d.mainnet ?? {};

const lines = [
  "# generated by scripts/sync-env.mjs — do not edit by hand",
  "",
  "NEXT_PUBLIC_NETWORK=testnet",
  "",
  `# Proved contract, testnet (${t.contractId ?? "not deployed"})`,
  `NEXT_PUBLIC_CONTRACT_TESTNET=${t.contractId ?? ""}`,
  "",
  `# Proved contract, mainnet (${m.contractId ?? "not deployed"})`,
  `NEXT_PUBLIC_CONTRACT_MAINNET=${m.contractId ?? ""}`,
  "",
  "# Soroban RPC",
  `NEXT_PUBLIC_RPC_TESTNET=${NETWORKS.testnet.rpcUrl}`,
  `NEXT_PUBLIC_RPC_MAINNET=${NETWORKS.mainnet.rpcUrl}`,
  "",
  "# Settlement asset",
  `NEXT_PUBLIC_ASSET_CODE_TESTNET=${t.assetCode ?? "PUSD"}`,
  `NEXT_PUBLIC_ASSET_CONTRACT_TESTNET=${t.asset ?? ""}`,
  `NEXT_PUBLIC_USDC_MAINNET=${m.asset || NETWORKS.mainnet.usdc}`,
  "",
];

const out = join(webDir, ".env.local");
writeFileSync(out, lines.join("\n"));
console.log("wrote", out);
if (!t.contractId) {
  console.warn("\nno testnet deployment recorded yet — run: pnpm run deploy:testnet");
}
